In [ ]:
import numpy as np

x_val = np.array([1,2])
y_val = np.array([2,2])

x,y = 5,6

print(x*x_val + y* y_val)

#coliner vector 1,2  2,2 are  possible to vectorized 1.x+2.y =17, 2.x+ 2.y=22 where x=5, y =6

In [ ]:
rs= np.array([17,22])

set_vec = np.array([[1,0],[1,0]])

print(np.linalg.solve(set_vec,rs))

#coliner vector  1,0  2,0 are not possible to vectorized 1.x+2.y =17, 0+ 0.y=22

In [ ]:
rs= np.array([19,29,54])

set_vec = np.array([[1,2,3],[1,2,6],[4,5,6]])

print(np.linalg.solve(set_vec,rs))


In [16]:
#EIGEN VECROR AND matrics

A= np.array([[1,2],[2,1]])

val=np.linalg.eig(A)
print(val)
L=val[0]
V=val[1]
print(L,V)

(array([ 3., -1.]), array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))
[ 3. -1.] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [22]:
#A.V= lenbda * V

A @ V.T [0]

array([2.12132034, 2.12132034])

In [31]:
A= np.array([[1,2,3],[2,3,1],[3,1,2]])
val=np.linalg.eig(A.T)
print(np.round(val[1],2))

[[-0.58 -0.79  0.21]
 [-0.58  0.21 -0.79]
 [-0.58  0.58  0.58]]
