In [2]:
import numpy as np 

In [1]:
arry= np.arange(160).reshape(16,10)
print(arry)

NameError: name 'np' is not defined

In [24]:
print([arry[:,i] for i in range(4)])

[array([ 0,  4,  8, 12]), array([ 1,  5,  9, 13]), array([ 2,  6, 10, 14]), array([ 3,  7, 11, 15])]


In [31]:
v= np.vectorize(lambda x : x**2)
print(v(arry))

[[    0     1     4     9    16    25    36    49    64    81]
 [  100   121   144   169   196   225   256   289   324   361]
 [  400   441   484   529   576   625   676   729   784   841]
 [  900   961  1024  1089  1156  1225  1296  1369  1444  1521]
 [ 1600  1681  1764  1849  1936  2025  2116  2209  2304  2401]
 [ 2500  2601  2704  2809  2916  3025  3136  3249  3364  3481]
 [ 3600  3721  3844  3969  4096  4225  4356  4489  4624  4761]
 [ 4900  5041  5184  5329  5476  5625  5776  5929  6084  6241]
 [ 6400  6561  6724  6889  7056  7225  7396  7569  7744  7921]
 [ 8100  8281  8464  8649  8836  9025  9216  9409  9604  9801]
 [10000 10201 10404 10609 10816 11025 11236 11449 11664 11881]
 [12100 12321 12544 12769 12996 13225 13456 13689 13924 14161]
 [14400 14641 14884 15129 15376 15625 15876 16129 16384 16641]
 [16900 17161 17424 17689 17956 18225 18496 18769 19044 19321]
 [19600 19881 20164 20449 20736 21025 21316 21609 21904 22201]
 [22500 22801 23104 23409 23716 24025 24336 24649 24964

In [70]:
##load data from website 
import requests, bs4 
import urllib


title = urllib.parse.quote_plus('Dolittle')
year=2020
url ='https://www.imdb.com/search/title/?title={0}&adult=include&view=simple&count=2&year={1}'.format(title ,year)
print(url)
data=requests.get(url)

data= bs4.BeautifulSoup(data.text,'html5lib')
itemDataText= data.select_one('div.lister-item .lister-item-content')

src =[ {'title' : itemDataText.select_one('.col-title span.lister-item-header span[title] a')} ]
itemData = {'title':.get_text().strip(),
            'rating': itemDataText.select_one('.col-imdb-rating').get_text().strip() }  
#itemData.update({'Download Full Movie':data.find(lambda tag:tag.name=="a" and "Download Full Movie" in tag.text).get('href')})
#itemData.update({'Download Full HD':data.find(lambda tag:tag.name=="a" and "Download Full HD" in tag.text).get('href')})
print(itemData)


https://www.imdb.com/search/title/?title=Dolittle&adult=include&view=simple&count=2&year=2020
{'title': 'Dolittle', 'rating': '5.6'}


In [5]:
s={'rank':1}

s['test']=1
s.update({'s':3})


{'rank': 1, 'test': 1, 's': 3} 12 2


In [ ]:
import progressbar
from time import sleep
bar = progressbar.ProgressBar(maxval=20, \
    widgets=[progressbar.Bar('#', '[', ']'), ' ', progressbar.Percentage()])
bar.start()
for i in range(20):
   print(1)
   bar.update(i+1)
   
bar.finish()